---
# This will install nagios

- name: remove php5
  yum: pkg={{ item }} state=absent
  with_items:
    - php

- name: install nagios and other repos
  yum: pkg={{ item }} state=present
  with_items:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - https://repo.nagios.com/nagios/7/nagios-repo-7-3.el7.noarch.rpm
    - centos-release-scl

- name: install nagios
  yum: pkg={{ item }} state=present
  with_items:
    - nagios
    - dejavu-lgc-sans-fonts
    - dejavu-lgc-sans-mono-fonts
    - graphviz-gd
    - perl-Crypt-DES
    - perl-Parse-RecDescent
    - php-mbstring
    - php-snmp
  notify: restart httpd

- name: install some useful nagios plugins
  yum: name={{ item }} state=present
  with_items:
   - nagios-nrpe
   - nagios-plugins-swap
   - nagios-plugins-users
   - nagios-plugins-procs
   - nagios-plugins-load
   - nagios-plugins-disk
   - nagios-plugins-ping
   - nagios-plugins-ssh
   - nagios-plugins-http

- name: create nagios config dir
  file: path=/etc/nagios/ansible-managed state=directory

- name: create nagios spool dir
  file: path=/var/log/nagios/spool/checkresults state=directory owner=nagios group=nagios

- name: configure nagios
  copy: src=nagios.cfg dest=/etc/nagios/nagios.cfg
  notify: restart nagios

- name: configure localhost monitoring
  copy: src=localhost.cfg dest=/etc/nagios/objects/localhost.cfg
  notify: restart nagios

- name: configure nagios services
  copy: src=ansible-managed-services.cfg dest=/etc/nagios/

- name: create the nagios object files
  template: src={{ item + ".j2" }}
            dest=/etc/nagios/ansible-managed/{{ item }}
  with_items:
    - webservers.cfg
    - dbservers.cfg
  notify: restart nagios

- name: start nagios
  service: name=nagios state=started enabled=yes
